### ISSUE TITLE
Update for pyOpenSSL 16.0.0

### ISSUE THREAD

**Issue by watucker** [cedadev/ndg_saml#4]
The OpenSSL.test package used by [ndg.saml.utils.pyopenssl](https://github.com/cedadev/ndg_saml/blob/bee0fb3272db5eef41fbb4acedeaa7c6e866248c/ndg/saml/utils/pyopenssl.py#L13) is no longer present in the current version of pyOpenSSL.

**Comment by philipkershaw** [comment]
Should be fixed now in devel
